/* AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
 * Public runtime config for the browser. Regenerate with `npm run build`. */
window.PROAI_ENV = {
  "SUPABASE_URL": "https://yiwgyovzohcwvqpwmesk.supabase.co",
  "SUPABASE_PUBLISHABLE_KEY": "sb_publishable_OMCnXrtMw-Dya2a1Z3g7HA_2GUzR0lb",
  "MIDTRANS_CLIENT_KEY": "",
  "MIDTRANS_IS_PRODUCTION": false
};
