// Generates proai-env.js (the browser's public runtime config) from environment
// variables. Run via `npm run build`. On a hosting platform, set the env vars in the
// dashboard and use `npm run build` as the build command.
//
// Resolution order for each value: process.env  ->  ./.env file  ->  built-in default.
// Only PUBLIC values are emitted here. Secrets (service_role, Midtrans SERVER key) are
// never written to this file.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

// Minimal .env parser (no dependency).
function loadDotEnv(file) {
  const out = {};
  try {
    const text = fs.readFileSync(file, 'utf8');
    for (const raw of text.split(/\r?\n/)) {
      const line = raw.trim();
      if (!line || line.startsWith('#')) continue;
      const eq = line.indexOf('=');
      if (eq === -1) continue;
      const key = line.slice(0, eq).trim();
      let val = line.slice(eq + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      out[key] = val;
    }
  } catch (_) { /* no .env file — fine */ }
  return out;
}

const fileEnv = loadDotEnv(path.join(ROOT, '.env'));
const pick = (k, def) => (process.env[k] != null ? process.env[k] : (fileEnv[k] != null ? fileEnv[k] : def));

const DEFAULTS = {
  SUPABASE_URL: 'https://yiwgyovzohcwvqpwmesk.supabase.co',
  SUPABASE_PUBLISHABLE_KEY: 'sb_publishable_OMCnXrtMw-Dya2a1Z3g7HA_2GUzR0lb',
  MIDTRANS_CLIENT_KEY: 'Mid-client--uirV-i8Evuc_hW2', // production client key (browser-safe)
  MIDTRANS_IS_PRODUCTION: 'true',
};

const env = {
  SUPABASE_URL: pick('SUPABASE_URL', DEFAULTS.SUPABASE_URL),
  SUPABASE_PUBLISHABLE_KEY: pick('SUPABASE_PUBLISHABLE_KEY', DEFAULTS.SUPABASE_PUBLISHABLE_KEY),
  MIDTRANS_CLIENT_KEY: pick('MIDTRANS_CLIENT_KEY', DEFAULTS.MIDTRANS_CLIENT_KEY),
  MIDTRANS_IS_PRODUCTION: String(pick('MIDTRANS_IS_PRODUCTION', DEFAULTS.MIDTRANS_IS_PRODUCTION)) === 'true',
};

const banner = '/* AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.\n' +
  ' * Public runtime config for the browser. Regenerate with `npm run build`. */\n';
const body = 'window.PROAI_ENV = ' + JSON.stringify(env, null, 2) + ';\n';

fs.writeFileSync(path.join(ROOT, 'proai-env.js'), banner + body);

console.log('Wrote proai-env.js:');
console.log('  SUPABASE_URL              =', env.SUPABASE_URL);
console.log('  SUPABASE_PUBLISHABLE_KEY  =', env.SUPABASE_PUBLISHABLE_KEY.slice(0, 16) + '…');
console.log('  MIDTRANS_CLIENT_KEY       =', env.MIDTRANS_CLIENT_KEY ? '(set)' : '(empty — checkout disabled)');
console.log('  MIDTRANS_IS_PRODUCTION    =', env.MIDTRANS_IS_PRODUCTION);
